version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consultation-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./consultation-backend
      dockerfile: Dockerfile
    container_name: consultation-backend
    restart: always
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5002
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge